### ISSUE TITLE
Chip: component documentation update

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components-design#8]
chip update

[ ] remove draggable chip from component and docs

[ ] remove input chip examples that show input chips outside of the context of a text input

[ ] remove editable chip ideas

[ ] remove icons from selection chip in component and docs

[ ] add keyboard navigation

[ ] verify screen reader behaviour documentation

**Comment by Spark450** [comment]
[Jira issue](https://goa-dio.atlassian.net/browse/DDIDS-1458?atlOrigin=eyJpIjoiZjgzYjM1YzhlODliNDdhODlhY2E4NzRmNzQ5MzRmNDQiLCJwIjoiaiJ9)

**Comment by twjeffery** [comment]
@Spark450 this one is updated in the Figma component library

https://www.figma.com/design/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Component-library-%7C-DDD?node-id=911-5909
